### ISSUE TITLE
Error in 1.17+ version

### ISSUE THREAD

**Issue by radimnemecek** [Harieo/Seasons#55]
There is error in new 1.17+ minecraft version. Could you please update and fix this problem?

```
[13:29:03] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Seasons v2.5.0
java.lang.NullPointerException: Cannot invoke "uk.co.harieo.seasons.plugin.configuration.SeasonsWorlds.getParsedCycles()" because "this.worldHandler" is null
	at uk.co.harieo.seasons.plugin.Seasons.getWorldCycle(Seasons.java:199) ~[?:?]
	at uk.co.harieo.seasons.plugin.models.effect.Effect.isPlayerCycleApplicable(Effect.java:162) ~[?:?]
	at uk.co.harieo.seasons.core.v1_13_R1.bad.HotSand.onMove(HotSand.java:35) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor93.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[server.jar:git-Paper-103]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[server.jar:git-Paper-103]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:git-Paper-103]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[server.jar:git-Paper-103]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1420) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:114) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$PosRot.handle(ServerboundMovePlayerPacket.java:16) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:36) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server.jar:git-Paper-103]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1348) ~[server.jar:git-Paper-103]
	at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[server.jar:git-Paper-103]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1327) ~[server.jar:git-Paper-103]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1320) ~[server.jar:git-Paper-103]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1458) ~[server.jar:git-Paper-103]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[server.jar:git-Paper-103]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[server.jar:git-Paper-103]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by Harieo** [comment]
This issue is not related to your server version.

If possible, would you be able to answer these questions:
- Was there an error when starting your server relating to seasons?
- When you start your server, does the message "Seasons has been loaded" appear before or after the error you've provided?
- When does this error happen? What caused it?

**Comment by radimnemecek** [comment]
After restart:

```
21:40:10[INFO] [Seasons] Loading Seasons v2.5.0

21:40:24[INFO] [Seasons] Enabling Seasons v2.5.0
21:40:24[INFO] [Seasons] 4 worlds have been disabled, 0 weathers have been disabled and 4 have been disabled
21:40:24[INFO] [Seasons] Preparing to load...
21:40:24[INFO] [Seasons] Seasons has detected modern Spigot (1.13+) and will adapt to use 1.13 implementation
```

No error now.

The problem was that this error popped up several times per second. In about an hour, the log file has about 5 GB.

This error began to appear by itself. I don't think anything caused the error. Before restart, I updated the paperspigot to the latest version. I have no idea where the problem might be.

**Comment by Harieo** [comment]
The issue revolved around Seasons not being able to load your worlds properly. The only fix we'd be able to make would be to stop the error coming up but the problem would still exist.

Are you happy that it's no longer happening?
